apiVersion: v1
kind: Service
metadata:
    name: dbServer
    labels:
        app: postgres
spec:
    type: ClusterIP
    ports:
     - port: 5432
       targetPort: postgres-port
       protocol: TCP
    selector:
        app: postgres
