apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp-deployment
  labels:
    app: userapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userapp
  template:
    metadata:
      labels:
        app: userapp
    spec:
      containers:
        - name: userapp
          image: milandj984/users-app:v1
          ports:
            - name: userapp-port
              containerPort: 80
      initContainers:
        - name: init-dbService
          image: busybox
          command: ['sh', '-c', 'until nslookup dbService; do echo waiting for dbService; sleep 2; done;']
