apiVersion: v1
kind: Service
metadata:
    name: userapp-service
    labels:
        app: userapp
spec:
    type: NodePort
    ports:
     - port: 80
       targetPort: userapp-port
       nodePort: 30005
       protocol: TCP
    selector:
            app: userapp
