pipeline {

    agent any
/*
	tools {
        maven "maven3"
    }
*/
    environment {
        registry = "milandj984/users-app"
        registryCredential = 'dockerhub'
        
//         gitBranch = "master"
//         gitUrl = "https://github.com/milandj984/jenkins-kubernetes.git"
        
        imageTag = "v$BUILD_NUMBER"
    }

    stages {
        
//         stage('Fetch code') {
//             steps {
//                 git branch: gitBranch, url: gitUrl
//             }
//         }
        
        stage('Dotnet Build') {
            steps {
                sh '''cd UserApp
                dotnet build -c Release'''
            }
//             post {
//                 success {
//                     echo 'Now Archiving...'
//                     archiveArtifacts artifacts: '**/target/*.war'
//                 }
//             }
        }

//         stage('UNIT TEST'){
//             steps {
//                 sh 'mvn test'
//             }
//         }
// 
//         stage('INTEGRATION TEST'){
//             steps {
//                 sh 'mvn verify -DskipUnitTests'
//             }
//         }

//         stage ('CODE ANALYSIS WITH CHECKSTYLE'){
//             steps {
//                 sh 'mvn checkstyle:checkstyle'
//             }
//             post {
//                 success {
//                     echo 'Generated Analysis Result'
//                 }
//             }
//         }
// 
//         stage('CODE ANALYSIS with SONARQUBE') {
// 
//             environment {
//                 scannerHome = tool 'mysonarscanner4'
//             }
// 
//             steps {
//                 withSonarQubeEnv('sonar-pro') {
//                     sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
//                    -Dsonar.projectName=vprofile-repo \
//                    -Dsonar.projectVersion=1.0 \
//                    -Dsonar.sources=src/ \
//                    -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
//                    -Dsonar.junit.reportsPath=target/surefire-reports/ \
//                    -Dsonar.jacoco.reportsPath=target/jacoco.exec \
//                    -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
//                 }
// 
//                 timeout(time: 10, unit: 'MINUTES') {
//                     waitForQualityGate abortPipeline: true
//                 }
//             }
//         }

        stage('Build App Image') {
            steps {
                script {
//                     dockerImage = docker.build registry + ":$imageTag"
                    dockerImage = docker.build("$registry:$imageTag", "./UserApp")
                }
            }
        }

        stage('Upload Image'){
            steps {
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push("$imageTag")
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Remove Unused docker image') {
            steps {
                sh '''docker rmi $registry:$imageTag
                docker rmi $registry:latest
                docker image prune -f --filter label=stage=builder'''
            }
        }

        stage('Kubernetes Deploy') {
            agent {label 'KOPS'}
                steps {
                    sh "helm upgrade --install --force userapp-stack /home/vagrant/jenkins-slave/workspace/users-app/UserApp/helm/userappcharts --set imagename=${registry}:${imageTag} --namespace default"
                }
            }
        }
}
